name = "bitcoin-dca-bot"
main = "src/index.ts"
compatibility_date = "2023-05-18"

[vars]
PURCHASE_AMOUNT_BTC = "0.00015" # 1回の購入金額, BTC 建てで入力. Bitbank 購入金額は0.0001 ~ 10.0 (BTC 建て), 換算はご自身でお願いします(https://osats.money/)

[triggers]
crons = ["0 1 * * *"]  # 毎日10:00 JSTに実行, 好きなタイミングに変更可能 (https://crontab.guru/)

[observability]
enabled = true # Cloudflare 上でLog を確認するためには true にする必要がある
