name = "bitcoin-dca-bot"
main = "src/index.ts"
compatibility_date = "2023-05-18"

[vars]
PURCHASE_AMOUNT_JPY = "1000"

[triggers]
crons = ["0 1 * * *"]  # 毎日10:00 JSTに実行

[observability]
enabled = true
